# Generated by Django 3.2.6 on 2022-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='consumed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='duetime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='remaining_time',
            field=models.IntegerField(default=0),
        ),
    ]
